config/routes.rb
Rails.application.routes.draw do
 
  root 'locations#index'
  resources :creatures

  resources :moves

  resources :locations

  devise_for :users

  get 'creature/:id/fight' => 'creatures#fight', :as => 'fight'
  get 'creature/:id/catch' => 'creatures#catch', :as => 'catch'
  get 'creature/:id/rename' => 'creatures#rename', :as => 'rename'
  

post '/form' do
    @url = "https://localhost:8080/#{params[:room]}"
    @comm = params['comm']
  uri = URI.parse(@url)
if params[:command]!= ""
  data = {"command" => "#{params[:command]}", "state" => $state}
else
  data = {"command" => nil, "state" => $state}
end

end

app/models/creature.rb
class Creature < ActiveRecord::Base
	has_many :moves
	belongs_to :user
	belongs_to :location
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  include CreaturesHelper
  # GET /creatures
  # GET /creatures.json
  def index
    @creatures = current_user.creatures
  end

  # GET /creatures/1
  # GET /creatures/1.json
  def show
    @creature = Creature.find(params[:id])
  end

  # GET /creatures/new
  def new
    @creature = Creature.new
  end

  # GET /creatures/1/edit
  def edit
  end



  def fight
    @creature = Creature.find(params[:id])
    @mycrea = current_user.creatures.find_by_id(6)

#@org = @team.org
#@group = @team.group

  end

  #def usemove
   # @usermove = Move.find(params[:id])
   # @oppocrea = Creature.find(params[:id])
   # @newhp = @oppocrea.hp - @usermove.damage
   # @oppcrea.update_attribute(:hp, @newhp)
   # redirect_to '/fight'
  #end

  #def minushp
   # @creature.hp = @creature.hp - move.damage
  #end

  def usemove
    @usermove = Move.find(params[:id])
    @oppocrea = Creature.find(params[:id])
    @newhp = @oppocrea.hp - @usermove.damage
    @oppcrea.update_attribute(:hp, @newhp)
    redirect_to '/fight'
  end

  def catch
    @oppocrea = Creature.find(params[:id])
    if @oppocrea.hp < 150
      @oppcrea.update_attribute(:user_id, current_user.id)
      redirect_to rename_path(@oppocrea)
    else
      redirect_to '/fight'
    end
  end

  def rename
  end


  # POST /creatures
  # POST /creatures.json
  def create
    @creature = Creature.new(creature_params)

    respond_to do |format|
      if @creature.save
        format.html { redirect_to @creature, notice: 'Creature was successfully created.' }
        format.json { render :show, status: :created, location: @creature }
      else
        format.html { render :new }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatures/1
  # PATCH/PUT /creatures/1.json
  def update
    respond_to do |format|
      if @creature.update(creature_params)
        format.html { redirect_to @creature, notice: 'Creature was successfully updated.' }
        format.json { render :show, status: :ok, location: @creature }
      else
        format.html { render :edit }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatures/1
  # DELETE /creatures/1.json
  def destroy
    @creature.destroy
    respond_to do |format|
      format.html { redirect_to creatures_url, notice: 'Creature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def form
  end

  #private
    # Use callbacks to share common setup or constraints between actions.
    def set_creature
      @creature = Creature.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creature_params
      params[:creature]
    end
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/_form.html.erb
<%= form_for(@creature) do |f| %>
  <% if @creature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creature.errors.count, "error") %> prohibited this creature from being saved:</h2>

      <ul>
      <% @creature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/creatures/edit.html.erb
<h1>Editing Creature</h1>

<%= render 'form' %>

<%= link_to 'Show', @creature %> |
<%= link_to 'Back', creatures_path %>

app/views/creatures/fight.html.erb
<form action="/form" method="post">

 <textarea id="result" rows="6" cols="40" value=>
You: <%= @mycrea.name %>
HP: <%= @mycrea.hp %>

Opponent: <%= @creature.name %>
HP: <%= @creature.hp %>
  </textarea><br>

Available Moves: <br>
<% @mycrea.moves.each do |move| %>
<%=move.name %> <br>
<%end%>
  <input type = "text" name="<%=:move%>" size="10"placeholder="Move">
  <input type = "submit">
</form>

<% @mycrea.moves.each do |move| %>

<%=@mycrea.name%> used <%=move.name %>
Damage: <%= move.damage %>
<% @creature.hp = @creature.hp - move.damage %>
<%= @creature.hp %>
	
<% end %>



	

app/views/creatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Creatures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creatures.each do |creature| %>
      <tr>
        <td><%= link_to 'Show', creature %></td>
        <td><%= link_to 'Edit', edit_creature_path(creature) %></td>
        <td><%= link_to 'Destroy', creature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creature', new_creature_path %>

app/views/creatures/new.html.erb
<h1>New Creature</h1>

<%= render 'form' %>

<%= link_to 'Back', creatures_path %>

app/views/creatures/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_creature_path(@creature) %> |
<%= link_to 'Back', creatures_path %>