config/routes.rb
Rails.application.routes.draw do
 
  root 'locations#index'
  resources :creatures

  resources :moves

  resources :locations

  devise_for :users

  get 'creature/:id/fight' => 'creatures#fight', :as => 'fight'
  get 'creature/:id/catch' => 'creatures#catch', :as => 'catch'
  get 'creature/:id/rename' => 'creatures#rename', :as => 'rename'
  

post '/form' do
    @url = "https://localhost:8080/#{params[:room]}"
    @comm = params['comm']
  uri = URI.parse(@url)
if params[:command]!= ""
  data = {"command" => "#{params[:command]}", "state" => $state}
else
  data = {"command" => nil, "state" => $state}
end

end

app/models/move.rb
class Move < ActiveRecord::Base
	belongs_to :creature
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  def usemove
   @usermove = Move.find(params[:id])
   @oppocrea = Creature.find(creature)
   @newhp = @oppocrea.hp - @usermove.damage
   @oppcrea.update_attribute(:hp, @newhp)
   redirect_to '/fight'
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  #def fight
    #@mycrea = current_user.creatures[0]
    #@oppocrea = Creature.find(params[:id])
  #end

  #def usemove
  #  @usermove = Move.find(params[:id])
  #  @oppocrea = Creature.find(params[:id])
  #  @newhp = @oppocrea.hp - @usermove.damage
  #  @oppcrea.update_attribute(:hp, @newhp)
  #  redirect_to '/fight'
  #end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params[:move]
    end

end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= form_for(@move) do |f| %>
  <% if @move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
      <% @move.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Moves</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>

app/views/moves/usemove.html.erb
<p id="notice"><%= notice %></p>

<%= @usermove.name %>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>