config/routes.rb
Rails.application.routes.draw do
 
  root 'locations#index'
  resources :creatures

  resources :moves

  resources :locations

  devise_for :users

  get 'creature/:id/fight' => 'creatures#fight', :as => 'fight'
  get 'creature/:id/catch' => 'creatures#catch', :as => 'catch'
  get 'creature/:id/rename' => 'creatures#rename', :as => 'rename'
  

post '/form' do
    @url = "https://localhost:8080/#{params[:room]}"
    @comm = params['comm']
  uri = URI.parse(@url)
if params[:command]!= ""
  data = {"command" => "#{params[:command]}", "state" => $state}
else
  data = {"command" => nil, "state" => $state}
end

end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :creatures
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
    @monsters = @location.creatures
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :x_coordinates, :y_coordinates)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
	def set_location
      @location = Location.find(params[:id])
    end
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br />
    <%= f.label :x_coordinates %>
    <%= f.number_field :x_coordinates %>
    <br />
    <%= f.label :y_coordinates %>
    <%= f.text_field :y_coordinates %>

  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<center>
<body id="location">
<!--<body background="assets/smallback.jpg" width="100%" height="100%">-->



<p> Previous Action: </p><p id="notice"><%= notice %></p>


<font face="Janda Elegant Handwriting" size="20">Listing Locations</font>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>GPS Coordinates</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.x_coordinates %>, <%= location.y_coordinates %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Location', new_location_path %>
<br>
</div>

<body id="locationright">
<img src="/assets/eve.png" alt="logo">
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<p align=right>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>

</p></center>
</body>

app/views/locations/new.html.erb
<center>
<body id="createlocation">
<font face="Janda Elegant Handwriting" size="20">New Location</font>

<%= render 'form' %>


<br>
<img src="/assets/twoeve.png" alt="logo" width="450" height="350"><br>
<%= link_to 'Back', locations_path %>
</center>

app/views/locations/show.html.erb
<center>
<body id="createlocation">

<p id="notice"><%= notice %></p>

<h1><%= @location.name %></h1>
<br />
<font face="Janda Elegant Handwriting" size="20">Monster Encountered!</font>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>HP</th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.hp %></td>
        <td><%= link_to 'Fight', fight_path(monster) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<img src="/assets/angry.png" alt="logo" width="300" height="350"><br>

<%= link_to 'Back', locations_path %>
</center>